sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"
install:
  - pip install -r requirements_test.txt
  - pip install -r requirements.txt
script:
  - cd happygif 
  - py.test --pep8 --cov ./
after_success:
  - coveralls